### PR TITLE
Fix bug with collapsed metadata fieldset being hidden in JSON dump plugin

### LINKED ISSUE #5088: Metadata fieldset in JSON registration options is not visible when lots of variables are selected
When no variables are selected:

Image

When lots of variables are selected:

Image

Also, might be a good idea to make the variable selection component wider, to account for the number (and also name length) of the variables

### PR DESCRIPTION
**Pull request by viktorvanwijk**
Closes #5088 

**Changes**

Ensure `overflow: visible` is set for the metadata variables fieldset in the JSON Dump plugin

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Dockerfile/scripts

  - [x] Updated the Dockerfile with the necessary scripts from the `./bin` folder

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js
Comment (robinmolen) [inline src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js:1]: I'm a bit conflicted, seeing how this is a different way of organizing the plugin configuration (the tabs are currently only used to move/group really different configuration).

I'm leaning towards resetting this to the way it was, and to fix the actual bug (the bootstrap styling).

Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js:1]: Just to be completely save (overwriting django styling can be tricky/have unexpected consequences), let's add this fix as a `openforms` custom styling. So i would add a `_fieldset.scss` file with some styling like:

```
/**
 * The django admin `.collapsed` styling on fieldset elements sets `overflow: hidden;`.
 * Seeing how we already hide the fieldset content in the javascript code,
 * the `overflow: hidden;` only hides the fieldset toggle (which we want to keep visible)
 */
.openforms-fieldset.collapsed {
  overflow: auto !important;
}
```

Then add the `openforms-fieldset` class to the Fieldset component, and everything should be fine :)

This would solve the problem of this bug, and also prevent other fieldsets from breaking.

**Review by robinmolen — CHANGES_REQUESTED** [review]

File: src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js
Comment (viktorvanwijk) [reply src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js:1]: > I'm leaning towards resetting this to the way it was, and to fix the actual bug (the bootstrap styling).

Yeah I fully agree. That's what I tried at first but couldn't get it to work, so this solution was just a workaround anyway. I had implemented your suggestion at first, but didn't have the `!important` tag, so it wasn't overriding anything. (S)CSS is not my greatest strength :see_no_evil:

File: src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js [hunk 1]
```diff
@@ -65,6 +65,7 @@ const JSONDumpOptionsForm = ({name, label, schema, formData, onChange}) => {
               defaultMessage="Metadata variables"
             />
           }
+          extraClassName="openforms-fieldset"
```
Comment (robinmolen) [inline src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js:68]: I was thinking about adding this styling to the component directly (i.e. set it as one of the default Fieldset classes). But this works as well 👍

**Review by robinmolen — APPROVED** [review]

File: src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js (hunk 1 above)
Comment (viktorvanwijk) [reply src/openforms/js/components/admin/form_design/registrations/json_dump/JSONDumpOptionsForm.js:68]: Yeah I figured it's the best to tread carefully here, as I haven't investigated ANY other fieldsets to which this change would also apply :grimacing:
