### PR TITLE
[#3382] Translation warnings for date,datetime placeholders

### LINKED ISSUE #3382: Translations: Date/Datetime components warn for translations of "dd-mm-yyyy" & "dd-MM-yyyy HH:mm"
### Product versie / Product version

2.1.x - 2.2.x

### Omschrijf het probleem / Describe the bug

Date and Datetime components in a form with translations will always show requirements for translations.
This is cause by their placeholders:
  "placeholder": "dd-mm-yyyy",
  "placeholder": "dd-MM-yyyy HH:mm",

This can only be solved by removing the placeholder.

### PR DESCRIPTION
**Pull request by vaszig**
Fixes #3382

### CODE REVIEW

File: src/openforms/js/components/formio_builder/translation.js [hunk 1]
```diff
@@ -124,7 +124,16 @@ export const extractComponentLiterals = component => {
...
+  const isDateOrDatetimeComponent = component.type === 'date' || component.type === 'datetime';
+  const dateOrDatetimeTranslatableProperties = allTranslatableProperties.filter(
+    property => property !== 'placeholder'
+  );
+
+  const literals = (
+    isDateOrDatetimeComponent ? dateOrDatetimeTranslatableProperties : allTranslatableProperties
+  )
     .filter(property => !isRegex(property))
     .map(property => get(component, property));
```
Comment (Viicos) [inline src/openforms/js/components/formio_builder/translation.js:138]: Maybe something like:

```suggestion
  const isDateOrDatetimeComponent = component.type === 'date' || component.type === 'datetime';

  const literals = allTranslatableProperties
    // Do not show warnings for date/datetime placeholders, they are not translatable:
    .filter(property => isDateOrDatetimeComponent ? property !== 'placeholder' : property)
    .filter(property => !isRegex(property))
    .map(property => get(component, property));
```

**Review by Viicos — APPROVED** [review]

File: src/openforms/js/components/formio_builder/translation.js (hunk 1 above)
Comment (sergei-maertens) [reply src/openforms/js/components/formio_builder/translation.js:138]: I like it, I'll apply it and make sure this PR gets merged.
