### PR TITLE
Broken react select styling for large values

### LINKED ISSUE #4802: React select styling issue with large values
### Product versie / Product version

3.0.0-alpha.0

### Customer reference

_No response_

### Omschrijf het probleem / Describe the bug

When the ReactSelect has a large value selected, the help icon will be pushed away. I think the element containing the selected value doesn't have a max-width, and just grows outside the ReactSelect element. 

Screenshot 2024-10-30 at 12 31 49

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by robinmolen**
Closes #4802

**Changes**

- Fixing the bug by ensuring that the `.admin-react-select` element can't grow beyond its max-inline-size
- Replaced the `DocumentTypes` and `CaseTypeSelect` select option html labels with simple text labels. The html labels are now added as a custom Option component for the ReactSelect. This means that the html labels will only be used when the option is presented in the dropdown, otherwise the simple text label will be used.
- Updated the storybook mock data to showcase large option labels for DocumentTypes and CaseTypeSelect

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [X] Checked copying a form
  - [X] Checked import/export of a form
  - [X] Config checks in the configuration overview admin page
  - [X] Problem detection in the admin email digest is handled

- Release management

  - [X] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [X] Ran `./bin/makemessages_js.sh`
  - [X] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [X] Commit messages refer to the relevant Github issue
  - [X] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js [hunk 1]
```diff
@@ -1,8 +1,9 @@
 import classNames from 'classnames';
 import {useField, useFormikContext} from 'formik';
 import PropTypes from 'prop-types';
-import {useContext, useEffect} from 'react';
+import React, {useContext, useEffect} from 'react';
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js:4]: we use the automatic jsx runtime, so the `React` import is not necessary :) (it's also not wrong)

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js [hunk 2]
```diff
@@ -40,30 +41,37 @@ const getDocumentTypes = async (apiGroupID, catalogueUrl) => {
     throw new Error('Loading available document types failed');
   }
   const documentTypes = response.data.sort((a, b) => a.omschrijving.localeCompare(b.omschrijving));
-  return documentTypes.map(({omschrijving, isPublished}) => ({
+  return documentTypes.map(({omschrijving}) => ({
     value: omschrijving,
-    label: (
+    label: omschrijving,
+  }));
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js:47]: isn't `isPublished` missing here?

File: src/openforms/scss/vendor/_react-select.scss [hunk 3]
```diff
@@ -25,4 +25,5 @@
     100%,
     var(--of-admin-select-max-inline-size)
   );
+  max-inline-size: var(--of-admin-select-max-inline-size);
```
Comment (sergei-maertens) [inline src/openforms/scss/vendor/_react-select.scss:28]: I've had to do this in more places in other projects and now I no longer understand how `clamp` works

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js (hunk 1 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js:4]: Ah okay, check. I'm also not sure why this was added... 😅
But i'll remove it :)

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js (hunk 2 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/registrations/objectsapi/fields/DocumentTypes.js:47]: Oh shit, your right..

File: src/openforms/scss/vendor/_react-select.scss (hunk 3 above)
Comment (robinmolen) [reply src/openforms/scss/vendor/_react-select.scss:28]: Yeah i also dont fully understand why the max-inline-size was needed.. Maybe because a child element was growing, instead of the `.admin-react-select`. So that the max-inline-size prevent all growth?

I think the `clamp` just allows the parent to grow between a min and max value, but it doesn't work fully for flexbox child elements? That they don't respect the set value, and grow beyond? The `.admin-react-select` is used in a `flex-wrap` environment, which might also complicate things..

But I haven't checked/investigated it so deeply..

**Review by sergei-maertens — APPROVED** [review]
