### PR TITLE
🐛 Switch ZGW registration backend to a field error

### LINKED ISSUE #3553: ZGW Registration backend validation error without message
### Product versie / Product version

latest @ open-forms.test.maykin.opengem.nl

### Omschrijf het probleem / Describe the bug

ZGW Registration backend configuration screen shows validation error indicator on the tab but no message is shown and data is not saved:

image

(via https://open-forms.test.maykin.opengem.nl/admin/forms/form/245/change/)

### Stappen om te reproduceren / Steps to reproduce

1. Create or edit a form
2. Added ZGW Apis to Registration backends
3. Enter the values as on the screenshot (copy-paste below)
````
Zaaktype: https://test.openzaak.nl/catalogi/api/v1/zaaktypen/2c1feba6-3163-4e15-9afa-fa4f01dcb4f9
IO type: https://test.openzaak.nl/catalogi/api/v1/informatieobjecttypen/1db73aba-cef4-42ec-bdf0-cd4c7c4f2514
Rol type: https://test.openzaak.nl/catalogi/api/v1/roltypen/335ba3f6-c55e-42d0-9b66-108edcce2e18
RSIN: 900222086
````
4. Save the form
5. Note the error indicator but no message.
6. On full page reload no data was saved

### Verwacht gedrag / Expected behavior

I'd expect validation error messages to be visible so we can fix the problem.

### Screen resolution

bigger

### Device

Desktop

### OS

Windows

### Browser

Firefox

### PR DESCRIPTION
**Pull request by Viicos**
Fixes #3553.

After taking a look at the test environment, I found at when a non field validation error was raised, it would not show up in the admin.

This fix switches the validation error to a specific field:
image

(validation error later attached to the `roltype`).

This also allows for non field errors to be displayed:

image

### CODE REVIEW

**Comment by Viicos** [comment]
Failing test is most likely related to time transition

File: src/openforms/js/components/admin/RJSFWrapper.js [hunk 1]
```diff
@@ -179,10 +181,12 @@ const FormRjsfWrapper = ({name, label, schema, uiSchema, formData, onChange, err
     }
     if (!errObj.__errors) errObj.__errors = [];
     errObj.__errors.push(msg);
+    console.log(errObj);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/RJSFWrapper.js:184]: please clean up your console.log statements :)

**Review by sergei-maertens — APPROVED** [review]
