### PR TITLE
[#4291] Fix logic triggers with boolean user defined variables

### LINKED ISSUE #4291: Logic triggers with boolean variables don't work correctly
### Product versie / Product version

latest (fdb19fdd6625e0281bdaed4a39a90f4f9150ec26)

### Omschrijf het probleem / Describe the bug

When I use a simple logic rule and use a boolean variable (checkbox component, boolean user defined variable...) as a trigger, this rule is not correctly serialized to JSON.

The resulting expression is:

```json
{
  "==": [
    {
      "var": "kanAfvalOphalen"
    },
    "true"
  ]
}
```

and it should be:

```json
{
  "==": [
    {
      "var": "kanAfvalOphalen"
    },
    true
  ]
}
```

UI representation:

image

The workaround is to use advanced logic instead of simple logic.

### Stappen om te reproduceren / Steps to reproduce

1. Add user defined variable `foo` with data type boolean
2. Add a simple logic rule
3. Select the variable `foo` in the "Als" dropdown
4. Select de operation "is gelijk aan"
5. Select "de waarde"
6. Select the comparison value "Ja"
7. Now, click the cog icon and click "Toon/verberg DSL weergave"

Any actions associated with this rule don't execute (for both true/false cases) because a string will never be equal to a boolean.

### Verwacht gedrag / Expected behavior

Selecting Yes/No in the dropdown configures an actual boolean in the JSON logic expression, and my actions execute properly.

### Screen resolution

None

### Device

None

### OS

None

### Browser

Chrome

### PR DESCRIPTION
**Pull request by vaszig**
Closes #4291

**Changes**

- Convert user defined boolean variables values from string to boolean type

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/logic/Trigger.js [hunk 1]
```diff
@@ -293,6 +294,14 @@ const Trigger = ({name, logic, onChange, error, withDSLPreview = false, children
...
         firstOperand = {var: triggerVariableKey};
     }
+  } else if (
+    triggerVariable?.source === VARIABLE_SOURCES.userDefined &&
+    triggerVariable.dataType === 'boolean'
+  ) {
+    firstOperand = {var: triggerVariableKey};
+    // cast from string to actual boolean
+    if (compareValue === 'true') compareValue = true;
+    if (compareValue === 'false') compareValue = false;
```
Comment (Viicos) [inline src/openforms/js/components/admin/form_design/logic/Trigger.js:304]:
```suggestion
    compareValue = STRING_TO_TYPE.bool(compareValue);
```

Or if you prefer to keep it this way, the import is unused
