### PR TITLE
🌐[#2819] Fix translations for password field.

### LINKED ISSUE #2819: Key of password field doesn't automatically update
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

And the translations also seem to be broken

### Stappen om te reproduceren / Steps to reproduce

- Create a form with a password field
- Update the label
=> Notice how the key doesn't change and if you go to the translations tab, there are no translations

### PR DESCRIPTION
**Pull request by CharString**
Closes #2819

### CODE REVIEW

**Comment by CharString** [comment]
Also fixes a small bug that the CI pointed out.

File: src/openforms/js/components/formio_builder/translation.js [hunk 1]
```diff
@@ -25,7 +25,9 @@ const LANGUAGES = getSupportedLanguages().map(([langCode]) => langCode);
  * the exact component type.
  * @type {string[]}
  */
-const ALWAYS_TRANSLATABLE_PROPERTIES = ['label', 'description', 'placeholder', 'tooltip'];
+const ALWAYS_TRANSLATABLE_PROPERTIES = ['label', 'description', 'placeholder', 'tooltip'].flatMap(
+  prop => [prop, 'basic.' + prop]
+);
```
Comment (CharString) [inline src/openforms/js/components/formio_builder/translation.js:30]: FormIO prepends the property names with 'basic.', because...

Comment (CharString) [reply src/openforms/js/components/formio_builder/translation.js:30]: Wait... This looks like something we've added... Which might be breaking things.

**Review by sergei-maertens — APPROVED** [review]
