### PR TITLE
:sparkles: [#3188] added duplicated keys warnings in form

### LINKED ISSUE #3188: Adding reusable form definitions with conflicting keys doesn't show warning
### Product versie / Product version

2.2.x

### Omschrijf het probleem / Describe the bug

- Create 2 reusable form definitions, both with a `textfield` component.
- Create a form.
- Add both form definitions created above
- Notice that you don't see a warning. If you save the form, you do get an error

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by bart-maykin**
Fixes #3188 

added warning for when there are components with duplicate keys
added test to see if warning shows if duplicate keys are pressent

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/FormStepDefinition.js [hunk 1]
```diff
@@ -104,6 +104,32 @@ const FormStepDefinition = ({
...
+  const duplicateKeys = getDuplicatedComponents(componentNamespace)
+    .filter(component =>
+      configuration.components.some(configComponent => configComponent.key === component.key)
+    )
+    .map(component => {
+      const componentLocations = getComponentLocations(formSteps, component);
+      const locations = componentLocations.map(location => {
+        return `${location.name} > ${component.label}`;
+      });
+      return `"${component.key}" (in ${locations.join(', ')})`;
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/FormStepDefinition.js:116]: this is not translatable, please use `intl.formatMessage(...)` for this so that we can properly localize/translate this.

File: src/openforms/js/components/admin/form_design/FormStepDefinition.js [hunk 2]
```diff
@@ -373,6 +399,32 @@ ConfigurationErrors.propTypes = {
...
+};
+
+const getComponentLocations = (formSteps, component) => {
+  return formSteps
+    .filter(step => step.configuration.components)
+    .map(step => {
+      if (step.configuration.components.some(stepComponent => component.key == stepComponent.key))
+        return step;
+    })
+    .filter(location => location);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/FormStepDefinition.js:425]:
```suggestion
    .filter(Boolean);
```
accomplishes the same and makes it look less like an incomplete lambda :)

File: src/openforms/js/components/admin/form_design/FormStepDefinition.js [hunk 3]
```diff
@@ -373,6 +399,32 @@ ConfigurationErrors.propTypes = {
...
+      return;
+    }
+
+    if (!duplicates.some(duplicate => duplicate.key === component.key)) duplicates.push(component);
+  });
+
+  return duplicates;
+};
+
+const getComponentLocations = (formSteps, component) => {
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/FormStepDefinition.js:418]: seems like only `component.key` is used, so perhaps that should be passed rather than the entire component?

**Review by sergei-maertens — APPROVED** [review]
