### PR TITLE
[#1275] Add warning if no login requried for familyMembers

### LINKED ISSUE #1275: Family members component crashes forms if no auth?

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #1275

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/AuthenticationWarning.js [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    const components = FormioUtils.flattenComponents(configuration.components || [], true);
+    const componentsWithCustomFieldTypes = Object.values(components).filter(
+        (component) => (CUSTOM_FIELD_TYPES.includes(component.type))
+    );
+
+    if (!componentsWithCustomFieldTypes.length) return null;
+
+    const formattedWarnings = componentsWithCustomFieldTypes.map((component, index) => (
+        <FormattedMessage
+            key={index}
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/AuthenticationWarning.js:22]: Not needed - the parent component already has the `key` prop

**Review by sergei-maertens — APPROVED** [review]
Created https://github.com/open-formulieren/open-forms/issues/1296 for some DRY-violations.
