### PR TITLE
[#3855] Catch errors when DMN plugin is not working

### LINKED ISSUE #3855: Allow for a better DMN user experience for both editor and end-user
Followup on #3730

**Tasks**

- [x] Extract the available input/output parameters from the DMN XML definition https://github.com/open-formulieren/open-forms/pull/3886 https://github.com/open-formulieren/open-forms/pull/3902
- [x] Show an error in the admin on the modal, when Camunda cannot be reached https://github.com/open-formulieren/open-forms/pull/3912
- [x] Result caching for given input parameters (pure function should be memoizable), though there is a risk the table is updated during multiple execution calls https://github.com/open-formulieren/open-forms/pull/3916
- [x] In the configuration modal, automatically select the plugin if there is only one option available. https://github.com/open-formulieren/open-forms/pull/3923
- [x] Show an error on the form, when a 500 error happened (for example because Camunda is down). Currently, nothing happens and no user feedback (network tab shows a 500). https://github.com/open-formulieren/open-forms-sdk/pull/647

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #3855 
Screenshot from 2024-02-20 11-48-07

Maybe the plugin ID field should be kept out of the boundary so that the user can select a different plugin in case of errors. Or they can just create a new action and delete the one with errors?

### CODE REVIEW

**Review by sergei-maertens — CHANGES_REQUESTED** [review]
Yes, let's bring the plugin field outside of the error boundary :) that makes more sense

**Comment by SilviaAmAm** [comment]
Screenshot from 2024-02-21 11-21-50

File: src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js [hunk 1]
```diff
@@ -104,13 +107,15 @@ const DecisionDefinitionVersionField = () => {
     // If decisionDefinitionId has changed, reset the value of the definition version if the new decision definition
     // does not have that version
     if (
-      values.decisionDefinitionVersion !== '' &&
-      !versionChoices.find(item => item[0] === values.decisionDefinitionVersion)
+      decisionDefinitionVersion !== '' &&
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:110]: shouldn't `decisionDefinitionVersion` be passed as dependency to `useAsync` too?

Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:110]: I thought no, because we don't need to refetch/update things if the version changes :thinking:

Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:110]: but it's used inside the hook in a check? if the version changes, the callback still has the old value and behaviour is not as expected.

Looking at it again, I think the `setFieldValue` call based on the available version choices actually belongs in a separate `useEffect`. And you can also simplify the logic IMO - if the definition ID changes, then the version should always be reset to make users aware they explicitly need to select the version. Version X for definition A does not have the same semantic meaning as Version X for definition B.

File: src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js [hunk 2]
```diff
@@ -24,32 +25,40 @@ const ERRORS = {
...
 
     const response = await get(DMN_DECISION_DEFINITIONS_LIST, {
-      engine: values.pluginId,
+      engine: pluginId,
     });
 
-    const definitionChoices = response.data.map(item => [item.id, item.label]);
-    setDecisionDefinitions(definitionChoices);
+    return response.data.map(item => [item.id, item.label]);
+  }, [pluginId, setFieldValue]);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:47]:
```suggestion
  }, [pluginId]);
```
this is not used in the hook, is it?

File: src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js [hunk 3]
```diff
@@ -24,32 +25,40 @@ const ERRORS = {
...
+
+    if (!pluginId) {
+      await setFieldValue('decisionDefinitionId', '');
+      return;
     }
-  }, [values.pluginId, setFieldValue]);
+
+    // If pluginId has changed, reset the value of the definition
+    await setFieldValue('decisionDefinitionId', '');
+  }, [pluginId, setFieldValue]);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:59]: What's the reason for calling these with `async`/`await`? I'd expected this to be a normal, sync `useEffect` hook and not `useAsync` :thinking:

File: src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js [hunk 4]
```diff
@@ -82,35 +96,37 @@ const DecisionDefinitionVersionField = () => {
...
 
     const response = await get(DMN_DECISION_DEFINITIONS_VERSIONS_LIST, {
       engine: pluginId,
       definition: decisionDefinitionId,
     });
 
-    const versionChoices = response.data.map(item => [item.id, item.label]);
-    setDecisionDefinitionVersions(versionChoices);
+    return response.data.map(item => [item.id, item.label]);
+  }, [pluginId, decisionDefinitionId, setFieldValue]);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:114]:
```suggestion
  }, [pluginId, decisionDefinitionId]);
```

File: src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js [hunk 5]
```diff
@@ -82,35 +96,37 @@ const DecisionDefinitionVersionField = () => {
...
-    ) {
-      setFieldValue('decisionDefinitionVersion', '');
+    if (!pluginId || !decisionDefinitionId) {
+      await setFieldValue('decisionDefinitionVersion', '');
+      return;
     }
+
+    // If decisionDefinitionId has changed, reset the value of the definition version
+    await setFieldValue('decisionDefinitionVersion', '');
   }, [pluginId, decisionDefinitionId, setFieldValue]);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:126]: here too I'd expect `useEffect` rather than `useAsync`

File: src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js (hunk 3 above)
Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:59]: I dont know, the docs say that setFieldValue returns a promise, so I thought that the async would be needed?

Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:59]: ah, that only really impacts what you do with the return value:

```js
foo = setFieldValue(...);
```
-> `foo` will be a promise so if you want to do something with the return value, you need to:

```js
foo = await setFieldValue(...)
// do more stuff with the return value
```

but since we don't use the return value of the (promise of) setFieldValue, it doesn't really matter. The side-effect is going to run no matter what.

I don't even know what the return value of `setFieldValue` promises looks like :D

Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/logic/actions/dmn/DMNActionConfig.js:59]: > If validateOnChange is set to true and there are errors, they will be resolved in the returned Promise.

right, so it returns validation errors. I don't see how that's useful for our needs, so you don't need to `await` it.

**Review by sergei-maertens — APPROVED** [review]
