### PR TITLE
Fix accidental mutation side effect breaking the Objects API v1 registration

### LINKED ISSUE #5035: (legacy) Object API registration: json_summary contains "duplicate" nodes
### Product versie / Product version

3.0.1

### Customer reference

DH

### Omschrijf het probleem / Describe the bug

The object API v1 json_summary seem to include the entire form in the first "step" with no values. But also includes each step with the data entered into the submission: 

example:
```json

    "record": {
        "typeVersion": 1,
        "data": {
            "data": {
                "step1: {
                    "buitenNederland": "JA",
                    "verzoek": {
                        "LTKnummer": "",
                        "HuidigeGeslachtsaanduiding": "MAN",
                        "voornaamWijzigen": "JA",
                        "voornamenWijzigen": "piet"
                    },
                    "_comment": "the following key's are not present in step 1 in the form",
                    "gegevensAanvrager": {
                        "Achternaam": "",
                        "tussenvoegselS": "",
                        "voorletterS": "",
                        "voornamen": "",
                        "BurgerServicenummer": "",
                        "Geboortedatum": "",
                        "geboorteland": "",
                        "Geboorteplaats": "",
                        "nationaliteit": ""
                    },
                    "oudersGetrouwd": "",
                    "huwelijkOuders": {
                        "datumHuwelijk": "",
                        "plaatsHuwelijk": "",
                        "landHuwelijk": ""
                    },
                    "bentUGeadopteerd": "",
                    "correspondentieadres": {
                        "Straat": "",
                        "Huisnummer": "",
                        "Huisletter": "",
                        "extraAdresregel": "",
                        "postcode": "",
                        "Woonplaats": "",
                        "land": "",
                        "eMailadres": "",
                        "telefoonnummer": ""
                    },
                    "UploadBijlagen1": [],
                    "UploadBijlagen2": [],
                    "UploadBijlagen3": [],
                    "UploadBijlagen4": []
                },
                "stap2": {
                    "gegevensAanvrager": {
                        "Achternaam": "uyuyt",
                        "tussenvoegselS": "",
                        "voorletterS": "jh",
                        "voornamen": "hg",
                        "BurgerServicenummer": "",
                        "Geboortedatum": "2025-01-01",
                        "geboorteland": "aaa",
                        "Geboorteplaats": "greg",
                        "nationaliteit": "reg"
                    },
                    "oudersGetrouwd": "NEE",
                    "huwelijkOuders": {
                        "datumHuwelijk": "",
                        "plaatsHuwelijk": "",
                        "landHuwelijk": ""
                    },
                    "bentUGeadopteerd": "JA",
                    "correspondentieadres": {
                        "Straat": "htrh",
                        "Huisnummer": "4",
                        "Huisletter": "",
                        "extraAdresregel": "",
                        "postcode": "1234aa",
                        "Woonplaats": "adsasdasd",
                        "land": "Nederland",
                        "eMailadres": "vasdasd@asdasdvv.nml",
                        "telefoonnummer": "xxxxxxxxxxx"
                    }
                },
                "bijlagen": {
                    "UploadBijlagen1": [
                        {
                            "url": "htt..."
                        }
                    ],
                    "UploadBijlagen2": [
                        {
                            "url": "htt..."
                        }
                    ],
                    "UploadBijlagen3": [
                        {
                            "url": "htt..."
                        }
                    ],
                    "UploadBijlagen4": [
                        {
                            "url": "htt..."
                        }
                    ]
                }
            }
```

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by sergei-maertens**
Closes #5035 

**Changes**

* Fixed wrong `FormVariable` records being created for components inside repeating groups
* Fixed unintended mutation adding the components of step 2-end to the configuration of step 1, leading to extra keys being submitted in the Objects API registration (legacy)
* Small quality of life thing: display the variable count on each tab in the variables editor
* Small refactor: removed some code duplication

The regression test + bugfix can be cherrypicked to the stable/3.0.x branch for backport purposes, the rest is for the main branch.

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Dockerfile/scripts

  - [x] Updated the Dockerfile with the necessary scripts from the `./bin` folder

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/variables/VariablesEditor.js [hunk 1]
```diff
@@ -36,12 +37,16 @@ const VariablesEditor = ({variables, onAdd, onDelete, onChange, onFieldChange})
         <Tabs>
           <TabList>
             <Tab hasErrors={componentVariables.some(variable => variableHasErrors(variable))}>
-              {intl.formatMessage(VARIABLE_SOURCES_GROUP_LABELS.component)}
+              {intl.formatMessage(VARIABLE_SOURCES_GROUP_LABELS.component)} (
+              {componentVariables.length})
```
Comment (vaszig) [inline src/openforms/js/components/admin/form_design/variables/VariablesEditor.js:41]: Nice!

**Review by vaszig — APPROVED** [review]

**Comment by sergei-maertens** [comment]
Backports: 
* 3.0.x: 3e6fd8d41042e9bb335af19eddb6d03b8cc13b04
* 2.8.x: fc3bacdedee85c17041445612fc2bfbfa125252f
