### PR TITLE
:bug: [#3375] fixed issue that would not show explanation template translation warnings

### LINKED ISSUE #3375: Translation warning for empty "Toelichtingssjabloon"
### Product versie / Product version

2.1.5

### Omschrijf het probleem / Describe the bug

internal: db16
When the "Toelichtingssjabloon" is empty it will return a translation warning for both languages. 
This should not happen when both versions (en + nl) of the field are empty.
image

Since the "toelichtingsjabloon" is optional and often left blank, this wanring should only occur if one version is different from the other.

### PR DESCRIPTION
**Pull request by bart-maykin**
fixes #3375 

- Added code to display translation warning only when not all filled in.
- Added playwright tests to test the translation warnings.

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js [hunk 1]
```diff
@@ -27,13 +34,20 @@ const extractMissingTranslations = (translations, tabName, fieldNames, fallbackF
...
+            Boolean(translationMapping[key])
+          );
+
+          if (!allOrNone(hasValue)) {
+            missingTranslations.push({
+              fieldName: LABEL_MAPPING[key],
+              language: languageCodeMapping[languageCode],
+              tabName: tabName,
+            });
+          }
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js:49]: Sorry but I don't understand at all what's happening here :confused:

**Comment by sergei-maertens** [comment]
The tests look nice and complete, nice job!

File: src/openforms/forms/tests/e2e_tests/test_translation_warnings.py [hunk 2]
```diff
@@ -0,0 +1,479 @@
...
+            / reverse("admin:forms_form_change", args=(form.pk,))
+        )
+
+        async with browser_page() as page:
+            await self._admin_login(page)
+            await page.goto(str(admin_url))
+
+            warning_list = page.locator("css=.messagelist")
+
+            await expect(warning_list).not_to_be_visible()
```
[the remark this answers is not in the document]
Comment (bart-maykin) [reply src/openforms/forms/tests/e2e_tests/test_translation_warnings.py]: Yes exactly because those translations have fallback fields it should trigger this bit of code
Screenshot from 2023-08-31 12-59-36

File: src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js [hunk 3]
```diff
@@ -13,10 +13,28 @@ import {extractMissingComponentTranslations} from './MissingComponentTranslation
...
   const defaultLangCode = LANGUAGES[0][0];
   const languageCodeMapping = Object.fromEntries(LANGUAGES);
   let skipWarningsFor = [];
+  const numOptionalTranslations = {};
+
+  const numLanguages = Object.keys(translations).length;
+  // count the amount of optional field translations
+  for (const [languageCode, mapping] of Object.entries(translations)) {
+    for (const [key, translation] of Object.entries(mapping)) {
+      if (fieldNames && (fieldNames || []).includes(key) && optionalFields.includes(key)) {
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js:32]:
```suggestion
      if (fieldNames && fieldNames.includes(key) && optionalFields.includes(key)) {
```
the `if fieldNames` already establishes that the variable is not `undefined`, `null` or otherwise falsy.

File: src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js [hunk 4]
```diff
@@ -26,21 +44,19 @@ const extractMissingTranslations = (translations, tabName, fieldNames, fallbackF
...
-          });
-        }
-      }
+      // Ignore optional fields that are all empty or filled in
+      if (numOptionalTranslations[key] === 0 || numOptionalTranslations[key] === numLanguages)
+        skipWarningsFor.push(key);
+
+      if (translation) continue;
+      if (skipWarningsFor.includes(key)) continue;
+      if (fieldNames && !(fieldNames || []).includes(key)) continue;
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/MissingTranslationsWarning.js:53]:
```suggestion
      if (fieldNames && !fieldNames.includes(key)) continue;
```
similar as above

**Review by sergei-maertens — APPROVED** [review]
