### PR TITLE
[#1924] Dark theme fixes

### LINKED ISSUE #1924: Dark scheme of the portal is unworkable
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The "dark scheme" of the Form designer is unworkable. Most of the text is unreadable and in some cases the action buttons as well.

### Stappen om te reproduceren / Steps to reproduce

Screenshot 2022-08-25 at 16 33 07
Screenshot 2022-08-25 at 16 33 31

### Verwacht gedrag / Expected behavior

Please disable it and make it so that the default is always applied. Now I am blocked because of this unfinished functionality.

### Screen resolution

_No response_

### Device

Desktop

### OS

iOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #1924

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/Editor.js [hunk 1]
```diff
@@ -9,14 +9,20 @@ const TinyMCEEditor = ({content, onEditorChange}) => {
   const editorRef = useRef(null);
   const tinyMceUrl = useContext(TinyMceContext);
   const intl = useIntl();
+  const useDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/Editor.js:12]: can you add a TODO for Django 4.2 - they now use explicit theme names rather than the media query approach: https://github.com/django/django/blob/main/django/contrib/admin/static/admin/css/dark_mode.css#L36

File: src/openforms/scss/components/builder/_builder.scss [hunk 2]
```diff
@@ -69,35 +69,33 @@ div.flatpickr-calendar.open {
   padding-top: 10px;
 }
 
-[ref='editForm'] {
```
Comment (sergei-maertens) [inline src/openforms/scss/components/builder/_builder.scss:72]: I think we had things scoped under this selector to prevent unexpected side effects with other unrelated components that happen to use the same classnames (it may have been django-admin-index). What's the reason for removing this?

File: src/openforms/scss/components/builder/_builder.scss [hunk 3]
```diff
@@ -69,35 +69,33 @@ div.flatpickr-calendar.open {
...
+    border-color: var(--border-color);
   }
 
-  .choices__list + .choices__input {
-    border: none;
-    border-radius: unset;
-    padding: 4px 0 4px 2px;
+  .choices__input {
+    background-color: var(--form-input-bg) !important;
+    border-color: var(--border-color) !important;
```
Comment (sergei-maertens) [inline src/openforms/scss/components/builder/_builder.scss:81]: why are the `!important` flags required? Preferably you override styles by using a more specific selector, which is reverted here in this PR.

File: src/openforms/scss/vendor/_rjsf-field.scss [hunk 4]
```diff
@@ -25,6 +25,11 @@
     input[type='email'] {
       width: $input-field-size; // override from admin/rjsf default
     }
+
+    select {
+      background-color: var(--form-input-bg) !important;
+      border-color: var(--border-color) !important;
+    }
```
Comment (sergei-maertens) [inline src/openforms/scss/vendor/_rjsf-field.scss:32]: maybe try using `color-scheme: dark` here too and see how that reacts? If we can avoid the `!important`, we should.

File: src/openforms/scss/components/builder/_builder.scss (hunk 2 above)
Comment (SilviaAmAm) [reply src/openforms/scss/components/builder/_builder.scss:72]: I removed because the the select dropdown in the editor has these classes but I couldn't find a parent with the `ref=editForm`. :thinking:

File: src/openforms/scss/vendor/_rjsf-field.scss (hunk 4 above)
Comment (SilviaAmAm) [reply src/openforms/scss/vendor/_rjsf-field.scss:32]: It gets a bit of a different colour:
Screenshot from 2022-10-19 12-36-53
Should I still go for it or leave the the colours?

**Comment by SilviaAmAm** [comment]
>     * The product edit form still has light-theme WYSIWYG fields, those are rendered via the django package afaik. These should also be adapted to use the correct theme (and preferably in a generic way)

I see there is this issue for it: https://github.com/jazzband/django-tinymce/issues/375. I'll look into it and see if I can figure out how to make it detect the dark theme!

File: src/openforms/js/components/admin/form_design/Editor.js [hunk 5]
```diff
@@ -9,14 +9,22 @@ const TinyMCEEditor = ({content, onEditorChange}) => {
...
       <Editor
         tinymceScriptSrc={tinyMceUrl}
         onInit={(evt, editor) => (editorRef.current = editor)}
         value={content}
-        init={{...tinyMceConfig, language: intl.locale}}
+        init={{
+          ...tinyMceConfig,
+          language: intl.locale,
+          skin: useDarkMode ? 'oxide-dark' : 'oxide',
+          content_css: useDarkMode ? 'dark' : 'default',
```
[the remark this answers is not in the document]
Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/Editor.js:26]: made an issue for this: https://github.com/open-formulieren/open-forms/issues/2215

File: src/openforms/scss/vendor/_rjsf-field.scss (hunk 4 above)
Comment (sergei-maertens) [reply src/openforms/scss/vendor/_rjsf-field.scss:32]: Hrm, probably because we explicitly set the background for the text inputs rather than using `color-scheme: dark` for those. Let's go with the explicit colors then - I'm curious which styles overrides this color though that require the `!important`.
