### PR TITLE
Bug/4727 crashing form after changing user variable to array

### LINKED ISSUE #4727: Changing variable type of user variable can crash the form editor
### Product versie / Product version

any

### Customer reference

DH 698

### Omschrijf het probleem / Describe the bug

When a user variable is changed from: object to array the form builders crashes:

`Uncaught TypeError: n.some is not a function`

it seems the value of the saved previous type causes this crash, since changing it to [] before switching to array does not crash. 

### Stappen om te reproduceren / Steps to reproduce

Add a user variable "object" with a value of {} (default)
Save form 
Change user variable type to array

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by robinmolen**
Closes #4727

**Changes**

Fixes the crashes on user variable dataType change, when a initialValue is defined. This crash happend when changing any dataType to the array dataType, because the component for the array dataType used the `.some` js array function. (It expected that the value was an array, so this function was used without any checks)

To resolve this situation, and possible similar situations in the future, the initialValue now gets transformed when the dataType changes. This transformation could result into losing the previous initialValue. To make sure that the dataType change is intentional, a confirmation message will be shown.

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/form-creation-form.js [hunk 1]
```diff
@@ -1229,6 +1243,39 @@ const FormCreationForm = ({formUuid, formUrl, formHistoryUrl, outgoingRequestsUr
...
+    // Check if the dataType change is intentional.
+    if (
+      propertyName === 'dataType' &&
+      checkIfInitialValueTransformationIsNeeded(propertyValue, originalVariable) &&
+      !window.confirm(
+        intl.formatMessage({
+          description:
+            'Changing user variable data type and transforming initial value confirmation message',
+          defaultMessage:
+            'Changing the data type requires the initial value to be changed, in some cases this could mean result in the initial value being reset to the default value. Are you sure that you want to do this?',
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/form-creation-form.js:1267]:
```suggestion
            'Changing the data type requires the initial value to be changed. This will reset the initial value back to the empty value. Are you sure that you want to do this?',
```

File: src/openforms/js/lang/nl.json [hunk 2]
```diff
@@ -271,6 +271,11 @@
     "isTranslated": true,
     "originalDefault": "minus"
   },
+  "5zEEiB": {
+    "defaultMessage": "Om het Datatype te veranderen, moet ook de beginwaarde aangepast worden. In sommige gevallen kan dit betekenen dat de beginwaarde wordt veranderd naar de standaard waarde van het Datatype. Weet je zeker dat je dit wilt doen?",
```
Comment (sergei-maertens) [inline src/openforms/js/lang/nl.json:275]: this is a bit too technical I think, the english version was simplified a bit.

Also please lower case "datatype"

File: src/openforms/js/lang/nl.json [hunk 3]
```diff
@@ -2622,6 +2627,11 @@
     "description": "JSON editor: object entry has empty key name",
     "originalDefault": "Set a key name before you can configure this variable"
   },
+  "vowYMF": {
+    "defaultMessage": "Weet je zeker dat je het Datatype wilt veranderen?",
+    "description": "Changing user variable data type and transforming initial value confirmation title",
+    "originalDefault": "Are you sure that you want to change the data type?"
+  },
```
Comment (sergei-maertens) [inline src/openforms/js/lang/nl.json:2634]: where is this message coming from? I only see one new `intl.formatMessage` call in this PR

File: src/openforms/js/components/admin/form_design/utils.js [hunk 4]
```diff
@@ -57,6 +57,74 @@ const checkKeyChange = (mutationType, newComponent, oldComponent) => {
   return newComponent.key !== oldComponent.key;
 };
 
+const checkIfInitialValueTransformationIsNeeded = (newType, originalVariable) => {
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/utils.js:60]: we only use the `initialValue` of the variable - do we need to pass the entire variable then? Looks like `originalValue` would be sufficient as an argument.

Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/utils.js:60]: I can't really picture situations where transformation is NOT needed, except for cases that are already broken like an array of strings but the variable type is set to "string".

Shouldn't we just always reset? Like even from string -> datetime: "foo" is not a valid datetime anyway, but a valid string, so maybe we can cut out some complexity?

File: src/openforms/js/components/admin/form_design/utils.js [hunk 5]
```diff
@@ -57,6 +57,74 @@ const checkKeyChange = (mutationType, newComponent, oldComponent) => {
...
+      return false;
+  }
+};
+
+const transformInitialValue = (newType, originalVariable) => {
+  switch (newType) {
+    case 'array':
+      if (
+        originalVariable?.initialValue == null ||
+        typeof originalVariable.initialValue === 'object'
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/utils.js:97]: `Array` is also object so I'm not sure how robust this is.

File: src/openforms/js/components/admin/form_design/utils.js [hunk 6]
```diff
@@ -57,6 +57,74 @@ const checkKeyChange = (mutationType, newComponent, oldComponent) => {
...
+      ) {
+        return [];
+      }
+      return [originalVariable.initialValue];
+
+    case 'boolean':
+      return undefined;
+
+    case 'int':
+      return Number.parseInt(originalVariable.initialValue);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/utils.js:107]: if `initialValue` is `'a'`, this will result in NaN and then we have an entirely different class of problems. I'm in favour of just always resetting to default empty value when you change type.

File: src/openforms/js/components/admin/form_design/utils.js (hunk 5 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/utils.js:97]: Ah yeah, it should have a `Array.isArray(...)` to make sure..

File: src/openforms/js/components/admin/form_design/utils.js (hunk 4 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/utils.js:60]: Mhh, i that thought also crossed my mind.. Maybe it is indeed best to always reset..

The only cases a transformation could be useful/nice is when a value changes to datatype `object` or when a date becomes a datetime (or something simular..). Or a simple value changes to array..

Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/utils.js:60]: let's just keep it simple and always reset then!

File: src/openforms/js/lang/nl.json (hunk 3 above)
Comment (robinmolen) [reply src/openforms/js/lang/nl.json:2634]: Ah yeah, I added this as the title for the new confirmation modal. At this moment this message isn't being used.
I'll remove it

File: src/openforms/js/components/admin/form_design/form-creation-form.js (hunk 1 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/form-creation-form.js]: I've changed this message and the dutch translation

File: src/openforms/js/components/admin/form_design/utils.js (hunk 4 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/utils.js]: I've removed it 👍

File: src/openforms/js/components/admin/form_design/utils.js (hunk 6 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/utils.js]: Yeah for all dataType's the transformation now just resets the value. So array becomes `[]`, object becomes `{}`, bool, int, and float return to `undefined`, and string, date, datetime and time return to `''`.

File: src/openforms/js/components/admin/form_design/utils.js (hunk 4 above)
Comment (robinmolen) [reply src/openforms/js/components/admin/form_design/utils.js]: Yeah, the entire object is indeed not needed.. I've changed it 👍

**Review by sergei-maertens — APPROVED** [review]

**Comment by sergei-maertens** [comment]
Backports:

* 2.8.x: 3f955b622184719155a92d6e340e2013e3368e67
* 2.7.x: 43272cd17e4966106a1102602b969def44114849
