### PR TITLE
Fix date/time min/max validation configuration not saving correctly

### LINKED ISSUE #2769: max/min dates/months/years are ignored in validation tab

### PR DESCRIPTION
**Pull request by sergei-maertens**
Fixes #2769

The layout component keys are not used as intermediate steps like with data containers, so the full namespaced path needs to be provided to the keys that actually write some configuration.

### CODE REVIEW

File: src/openforms/js/components/form/edit/date-edit-form.js [hunk 1]
```diff
@@ -62,34 +63,31 @@ const getMinMaxValidationEditForm = (fieldName, componentType) => {
           ) {
             return false;
           }
-          const upperCasedFieldName = fieldName.charAt(0).toUpperCase() + fieldName.substring(1);
-          const attrName = `enable${upperCasedFieldName}Input`;
-          const isFixedValue = data?.openForms[fieldName]?.mode === 'fixedValue';
-          return isFixedValue && !data[attrName];
```
Comment (sergei-maertens) [inline src/openforms/js/components/form/edit/date-edit-form.js:68]: @SilviaAmAm you seem to have touched this most recently, I grepped the codebase for `enable.*input` (case insensitive) and couldn't find any uses and it seems to work without. Do you remember if/why this was needed? From the git history it seemed like a leftover from my experiments/prototyping that should've been cleaned up before.

Comment (SilviaAmAm) [reply src/openforms/js/components/form/edit/date-edit-form.js:68]: No, i don't remember why this was needed :S

Comment (sergei-maertens) [reply src/openforms/js/components/form/edit/date-edit-form.js:68]: good riddance then :)

**Review by pi-sigma — APPROVED** [review]
