### PR TITLE
Fix modal crash

### LINKED ISSUE #1790: Clicking the link to display forms affected by changing a reusable form definition crashes the form builder
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

Clicking the link in the warning in the screenshot crashes the editor:

image

Error from dev console:

image

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

No crash

### Screen resolution

_No response_

### Device

_No response_

### OS

_No response_

### Browser

Brave Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by sergei-maertens**
Fixes #1790

This PR also fixes an import bug that I noticed while trying to import a form to reproduce the original issue.

### CODE REVIEW

File: src/openforms/js/components/admin/tables/ChangelistColumn.js [hunk 1]
```diff
@@ -6,6 +6,8 @@ const ChangelistColumn = ({objProp, isBool = false, children}) => {
   return null;
 };
 
+ChangelistColumn.tableRole = 'column';
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/tables/ChangelistColumn.js:9]: I decided to use the react-tabs approach instead :)

**Review by SilviaAmAm — APPROVED** [review]
Does the fix for the import need to be backported?

**Comment by sergei-maertens** [comment]
> Does the fix for the import need to be backported?

I don't think so, the performance updates were post 2.0.x, but I'll make sure to confirm.
