### PR TITLE
Layout fixes / declutter the configuration options

### LINKED ISSUE #4969: Feedback 3.0.0-apha
**Needs fixing**

* [x] Introductie-pagina is verwarrend met toelichtingssjabloon: Vervang de naam "Introductie-pagina" met "Optionele introductie-pagina"
* [x] Formulier stap configuratie velden springen over het scherm.
* [x] the `default_map_tile_layers_json` fixture is not loaded (and doesn't use natural keys)
* [x] Submission limits seem to reset when saving the form

**To discuss**

- ~~Objects API prefill -> the retrieved object is not actually saved in a variable, only the derived properties~~ keep it as it is

### PR DESCRIPTION
**Pull request by sergei-maertens**
Partly closes #4969

**Changes**

* Added storybook stories and some global configuration (for TinyMCE)
* Organized "form" tab in fieldsets
* Vertically stack form step configuration fields

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Dockerfile/scripts

  - [x] Updated the Dockerfile with the necessary scripts from the `./bin` folder

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/story-decorators.js [hunk 1]
```diff
@@ -59,12 +63,29 @@ export const FormDecorator = (Story, {args}) => (
...
+      ],
+      translationEnabled: false,
     }}
   >
     <Story />
   </FormContext.Provider>
 );
 
+export const TinyMceDecorator = Story => (
+  <TinyMceContext.Provider value="/static/tinymce/tinymce.min.js">
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/story-decorators.js:84]: this will need to be relative for the deployed storybook
