### PR TITLE
[#4533] Fix onFieldChange in upload submission csv checkbox (ObjectsAPI)

### LINKED ISSUE #4533: Upload submission CSV checkbox does not work in Objects API
### Product versie / Product version

latest

### Customer reference

_No response_

### Omschrijf het probleem / Describe the bug

Trying to check `Upload submission CSV` checkbox we get an error like the one below. The field is not updated when we click it and therefore we have an empty string in the data that we send to the backend.

image

image

### Stappen om te reproduceren / Steps to reproduce

1. Add a registration backend
2. Choose Objects API registration
3. Choose Legacy or Variables Mapping (we see the problem in both)
4. Check the `Upload submission CSV` and try to save the form

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by vaszig**
Closes #4533

- Updated `onChange` event in the checkbox in Objects API. There was a problem for both legacy and the new version, since the value of the checkbox would always be `"false"` 

[Describe the changes here]

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js [hunk 1]
```diff
@@ -183,7 +183,10 @@ const LegacyConfigFields = ({index, name, schema, formData, onFieldChange}) => {
           id="root_uploadSubmissionCsv"
           name="uploadSubmissionCsv"
           value={uploadSubmissionCsv}
-          onChange={onFieldChange}
+          checked={uploadSubmissionCsv}
+          onChange={e =>
+            onFieldChange({target: {name: 'uploadSubmissionCsv', value: !uploadSubmissionCsv}})
```
Comment (vaszig) [inline src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:188]: I chose to go this way instead of updating `onFieldChange ` https://github.com/open-formulieren/open-forms/blob/master/src/openforms/js/components/admin/form_design/registrations/objectsapi/ObjectsApiOptionsFormFields.js#L70 with nested if statements for possible boolean values. If you think it would be better I can change this.

Comment (Viicos) [reply src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:188]: This looks better to me as well

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js [hunk 2]
```diff
@@ -183,7 +183,10 @@ const LegacyConfigFields = ({index, name, schema, formData, onFieldChange}) => {
           id="root_uploadSubmissionCsv"
           name="uploadSubmissionCsv"
           value={uploadSubmissionCsv}
-          onChange={onFieldChange}
+          checked={uploadSubmissionCsv}
```
Comment (Viicos) [inline src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:186]: I haven't checked but can't this `checked` prop be inferred by the `Checkbox` component itself from the `value` prop?

Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:186]: I'd expect React warnings in the console here because an `input` element can only get string values :thinking:

Comment (vaszig) [reply src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:186]: If I remove it from here it doesn't appear in the html. And in the component itself (https://github.com/open-formulieren/open-forms/blob/master/src/openforms/js/components/admin/forms/Inputs.js#L99) I don't see `value` (it comes from the extra props) so how can this be inferred?Could you please elaborate?

Comment (vaszig) [reply src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:186]: I don't get any react warnings for this, but I do get though a lot for `objecttypeVersion` :

_Invalid prop `formData.objecttypeVersion` of type `number` supplied to `LegacyConfigFields`, expected `string`_

Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:186]: `value` is pretty meaningless for checkboxes, did a checkup on the HTML spec. In non-react code, the `value` is what would be sent to the server when the checkbox is checked, but in React this doesn't make any sense - we just track whether it's checked or not, so probably best to omit `value` entirely for the checkbox. All that matters is `checked`.

Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:186]: yeah, let's ignore those for now :(

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js [hunk 3]
```diff
@@ -183,7 +183,10 @@ const LegacyConfigFields = ({index, name, schema, formData, onFieldChange}) => {
           id="root_uploadSubmissionCsv"
           name="uploadSubmissionCsv"
           value={uploadSubmissionCsv}
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/registrations/objectsapi/LegacyConfigFields.js:185]:
```suggestion
```

File: src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js [hunk 4]
```diff
@@ -214,7 +214,10 @@ const V2ConfigFields = ({index, name, schema, formData, onFieldChange, onChange}
           id="root_uploadSubmissionCsv"
           name="uploadSubmissionCsv"
           value={uploadSubmissionCsv}
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/registrations/objectsapi/V2ConfigFields.js:216]:
```suggestion
```

**Review by sergei-maertens — CHANGES_REQUESTED** [review]

**Review by sergei-maertens — APPROVED** [review]

**Comment by sergei-maertens** [comment]
Backport: 063ee6a76fb8503c695708d9c611a86066745c10
