### PR TITLE
[#4432] Add an error boundary to the registration summary

### LINKED ISSUE #4432: Add error-boundary to the registration modal in the variables tab
### Product versie / Product version

latest (pre 2.7)

### Customer reference

_No response_

### Omschrijf het probleem / Describe the bug

All my hard work gets lost if Objects API is not reachable and I switch to the variables tab to assign variables.

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by Viicos**
Closes #4432

**Changes**

Not sure if this is the best place to put it

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummaryList.js [hunk 1]
```diff
@@ -35,7 +36,12 @@ const RegistrationSummary = ({
   const [modalOpen, setModalOpen] = useState(false);
 
   return (
-    <>
+    <ErrorBoundary
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummaryList.js:39]: I think moving it inside the modal is best, since the errors trigger during opening the modal, no?

```jsx
<ErrorBoundary>
  {variableConfigurationEditor}
  <SubmitRow>...</SubmitRow>
</ErrorBoundary>
```
etc.

Comment (Viicos) [reply src/openforms/js/components/admin/form_design/variables/registration/RegistrationsSummaryList.js:39]: I added it here as we may also have a crash when rendering the summary (for Objects API this the `path > to > target` thing)
