### PR TITLE
[#3283] Remove oldstyle appointments flow

### LINKED ISSUE #3283: Deprecations to remove in 3.0
A list of breaking changes to make when we get to version 3.0

<kbd>CTRL</kbd> + <kbd>F</kbd> on `DeprecationWarning` in the backend to find more.

- ~~INVESTIGATE: can we keep existing endpoints on /api/v2/ and new ones to /api/v3/ so we don't have to move everything at once?~~ Resolving by marking most of the API private API

- Appointments #4872 
    - [x] Remove old-style (form.io based) appointment flow
        - [x] most of `appointments.utils`
        - [x] extracting the appointment data from a submission
        - [x] Frontend code to manage appointment (tab)
        - [x] Remove support for fixed customer fields
    - [x] Remove "invalid input serializer -> return empty result list" in favour of raising a validation error exception
- Formio
    - [x] Remove `fd_translations_converter` module (this will affect exports < 3.0 that have legacy translations) #4828
    - [x] #3718
    - [x] Drop password component #4842
- Form design
    - [x] Remove 'formStep' in location action in favour of `formStepUuid` #4892 
    - [x] Make `FormDefinitionSerializer.name` `readOnly` (name is set via translations) @stevenbal 
    - [x] Delete `_data` model field https://github.com/open-formulieren/open-forms/blob/8f7b003e285893a158036dfc54ffd58f478bd12d/src/openforms/submissions/models/submission_step.py#L102
- Styling/NL DS
    -  [x] Remove compatibility shims from `of-page-header-*` and `of-page-footer-*` in favour of `utrecht-page-header-*` and `utrecht-page-footer-*` tokens @robinmolen 
        - `components/_page-header.scss`
        - `components/_page-footer.scss`
- Registration:
   - [x] Objects API/ZGW groups shouldn't have fields nullable
   - [x] Remove objecttype URL -> UUID import converter hook @robinmolen 
   - ~~Remove document type conversion hook (if it exists)~~
   - ~~Remove documenttype URLs - auto migrate where possible (management command to be added in 2.8.x?)~~
   - [x] Document migration procedures
   - [x] Remove automatic StUF-ZDS Utrecht extension conversion @robinmolen
   - [x] Remove (export/import) support/converter for single-registration backend configuration @robinmolen 

- Authentication
    - [x] Remove legacy machtigen context @sergei-maertens 
    - ~~#4890~~

- Misc
    - [x] Remove `/api/v2/location/get-street-name-and-city` in favour of `/api/v2/geo/address-autocomplete` @robinmolen
    - [x] Normalize API endpoints to use dashes rather than underscores
    - [x] Remove OR filtering in the FD endpoint: https://github.com/open-formulieren/open-forms/pull/3542
    - [x] Remove the null=True from `TemporaryFileUpload.submission` FK @sergei-maertens

### PR DESCRIPTION
**Pull request by vaszig**
Closes #3283 partly

**Changes**

- Updated code to adhere to the new appointments flow
- Now we do not extract the appointment data from a submission
- Removed frontend/admin code to manage appointment (tab)
- Removed support for fixed customer fields
- Removed "invalid input serializer -> return empty result list" in favour of raising a validation error exception

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/Appointments.js
Comment (robinmolen) [inline src/openforms/js/components/admin/form_design/Appointments.js:1]: I this file can be removed entirely :)

File: src/openforms/js/components/admin/form_design/form-creation-form.js
Comment (robinmolen) [inline src/openforms/js/components/admin/form_design/form-creation-form.js:1]: Lets just remove these items :)

File: src/openforms/emails/templates/emails/templatetags/appointment_information.html [hunk 1]
```diff
@@ -53,17 +53,12 @@ <h2 style="margin: 1em 0; font-size: 1.3em;">{% trans "Your contact details" %}<
     </table>
 
     <p>
-        {% trans "If you want to cancel or change your appointment, you can do so below." %}
+        {% trans "If you want to cancel your appointment, you can do so below." %}
     </p>
     <p>
-        <a href="{{ appointment_cancel_link }}" rel="nofollow">{% trans "Cancel appointment" %}</a>
+        {% trans "In case you want to modify it you have to cancel it and then create a new one." %}
```
Comment (robinmolen) [inline src/openforms/emails/templates/emails/templatetags/appointment_information.html:59]: I think the previous message was a bit nicer/more descriptive.

```suggestion
        {% trans "If you wish to change your appointment, please cancel it using the link below and create a new one." %}
```

File: src/openforms/appointments/tasks.py [hunk 2]
```diff
@@ -21,7 +18,7 @@
     ignore_result=False,
     once={"graceful": True},  # do not spam error monitoring
 )
-def maybe_register_appointment(submission_id: int) -> None | str:
+def register_appointment(submission_id: int) -> None | str:
```
Comment (robinmolen) [inline src/openforms/appointments/tasks.py:21]: Shouldn't this task be removed?

Comment (vaszig) [reply src/openforms/appointments/tasks.py:21]: No, this was discussed with Sergei and we decided that this is the correct way to do it (as a celery task). We just remove the old-flow parts from the task itself.

Comment (robinmolen) [reply src/openforms/appointments/tasks.py:21]: Ahhh okay, check 👍

File: src/openforms/appointments/management/commands/appointment.py [hunk 3]
```diff
@@ -5,6 +5,7 @@
 from django.core.management.base import CommandError
 from django.db.models import Q
 
+from openforms.appointments.base import CustomerDetails
```
Comment (robinmolen) [inline src/openforms/appointments/management/commands/appointment.py:8]: Import for CustomerDetails already exists

File: docs/manual/forms/examples/appointment_creation.rst [hunk 4]
```diff
@@ -1,83 +0,0 @@
...
-
-12. (Optioneel) Sleep een **Telefoonnummer** component op het witte vlak, vul de volgende
-    gegevens in en druk daarna op **Opslaan**:
-
-   * **Label**: Telefoonnummer
-
-13. Klik op het tabblad **Afspraken**.
-14. Kies de juiste componenten voor elke veld in dit tabblad.
-
-.. image:: _assets/appointment_creation_2_2.png
```
Comment (sergei-maertens) [inline docs/manual/forms/examples/appointment_creation.rst:73]: this image can be deleted too

File: src/openforms/appointments/tasks.py [hunk 5]
```diff
@@ -21,37 +18,20 @@
...
```
Comment (sergei-maertens) [inline src/openforms/appointments/tasks.py:21]: I'd stick with the original task name though, the `maybe_` prefix indicates that the task itself may not do anything at all. This is done so that the logic to act or not act is contained in the task itself (in this task `NoAppointmentForm` can be raised and then nothing is done).

The location where the task is scheduled then reads more natural:

* maybe we need to register an appointment, then
* maybe run pre-registration, then
* (definitely) generate the summary PDF, then
* maybe run registration, then
* maybe send a confirmation email

etc.

From the scheduling point of view, you don't know what will run or not, and while you can check it in there, that greatly breaks the loose coupling because you end up with a "god function" that understands the whole system. We don't do that, instead we set up the chain of tasks to execute and use naming conventions to indicate what will or might happen.

File: src/openforms/appointments/core.py [hunk 6]
```diff
@@ -116,5 +115,4 @@ def book_for_submission(submission: Submission) -> str:
         logevent.appointment_register_failure(appointment_info, plugin, e)
         raise AppointmentRegistrationFailed("Unable to create appointment") from e
 
-    cancel_previous_submission_appointment(submission)
```
Comment (sergei-maertens) [inline src/openforms/appointments/core.py:119]: considering this whole function is new-style appointments only, I'm not so sure about this line being removed :thinking:

File: src/openforms/submissions/query.py
Comment (sergei-maertens) [inline src/openforms/submissions/query.py:1]: if we remove previous_submission, do we need the copy method at all? Seems like it's only used in the appointments app. That would be a really nice cleanup if we can get rid of it!

File: src/openforms/emails/templatetags/appointments.py [hunk 7]
```diff
@@ -22,7 +22,7 @@ def appointment_information(context):
     else:
         template_name = "emails/templatetags/appointment_information.html"
 
-    # check for new style appointments
+    # check for appointments
     submission = context["_submission"]
     appointment = get_appointment(submission)
     plugin_id = appointment.plugin if appointment else ""
```
Comment (sergei-maertens) [inline src/openforms/emails/templatetags/appointments.py:28]: Shouldn't this now basically be an `assert appointment` because it doesn't make sense to use this tag if there's no appointment?

**Review by sergei-maertens — COMMENTED** [review]
OMG so much code being removed it's like it's almost Christmas!

File: src/openforms/appointments/core.py (hunk 6 above)
Comment (vaszig) [reply src/openforms/appointments/core.py:119]: I am not sure that I understand your point. I removed it because we do not have to deal with an extra function in order to cancel an appointment (we have `CancelAppointmentView`) right?And basically I have removed the whole function from `appointments/utils.py`.

Comment (sergei-maertens) [reply src/openforms/appointments/core.py:119]: I was wrong - this was incorrectly added when the new-style appointments was created and the removal is correct

File: src/openforms/js/components/admin/form_design/form-creation-form.js [hunk 8]
```diff
@@ -1,6 +1,6 @@
 import {produce} from 'immer';
 import cloneDeep from 'lodash/cloneDeep';
-import getObjectValue from 'lodash/get';
+// import getObjectValue from 'lodash/get';
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/form-creation-form.js:3]:
```suggestion
```

**Review by sergei-maertens — CHANGES_REQUESTED** [review]
and obviously the CI failures need to be looked into!

**Review by sergei-maertens — APPROVED** [review]

**Comment by sergei-maertens** [comment]
YEET

image
