### PR TITLE
[#2798] Update options values automatically

### LINKED ISSUE #2798: Auto-generation of Select (and radio/checkbox) values from labels is broken
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When you add a Select component to the form, you can define the values for the component in a tabular form.

This used to generate a (slugified) value from the label entered, reducing the amount of typing needed by form designers. This no longer works - the value column stays empty.

This probably applies to other values/data components too like the radio/checkboxes components.

### Stappen om te reproduceren / Steps to reproduce

1. Go to the form designer in the admin
2. Drag a "Keuzelijst" component into the dropzone
3. Fill out a label "Optie 1" for the first choice
4. Observe that the 'value' column stays empty

### Verwacht gedrag / Expected behavior

Values are derived from labels as default suggestion.

### Screen resolution

None

### Device

None

### OS

None

### Browser

Chrome

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #2798

### CODE REVIEW

File: src/openforms/js/components/formio_builder/builder.js [hunk 1]
```diff
@@ -368,15 +368,18 @@ const FormIOBuilder = ({
...
+          data: {
+            ...newComponentConfiguration,
+            openForms: {
+              ...(newComponentConfiguration?.openForms || {}),
+              translations: translations,
+            },
           },
         },
-      };
+        {fromSubmission: false}
```
Comment (SilviaAmAm) [inline src/openforms/js/components/formio_builder/builder.js:381]: It seems that here https://github.com/formio/formio.js/blob/v4.13.13/src/components/_classes/component/Component.js#L2632
formio does this check on `fromSubmission`. Before we added the custom `onChange` for the translations, the `fromSubmission` flag was undefined. The place where this flag gets set is the `setSubmission` function https://github.com/formio/formio.js/blob/v4.13.13/src/Webform.js#L783. 
Not really sure yet what this `fromSubmission` function means, but this seems to solve our problem

Comment (sergei-maertens) [reply src/openforms/js/components/formio_builder/builder.js:381]: I think it tracks if there was existing data that was loaded (like when you resume a paused form in our SDK), so then it won't override the submission data with calculated data because it was persisted already at some point.

I can't find any references to it in the documentation, only in the source code, but it seems that setting it to false here would be correct usage because we're doing programmatic stuff behind the scenes.

Comment (SilviaAmAm) [reply src/openforms/js/components/formio_builder/builder.js:381]: The problem with setting the flag here to false is that then I think the component is not updated, so the translations are no longer updated.

The `setValue` works better than the `setSubmission`, but any new translations are not added. I think it may be a matter of findingin which order the different updates have to happen so that the component is rendered with all the updates :see_no_evil:

File: src/openforms/forms/tests/e2e_tests/test_form_designer.py [hunk 2]
```diff
@@ -351,6 +351,48 @@ async def test_enable_translations_and_create_new_step(self):
...
+        async with browser_page() as page:
+            await self._admin_login(page)
+            await page.goto(str(admin_url))
+            await page.get_by_role("tab", name="Steps and fields").click()
+
+            # Drag and drop a component
+            await drag_and_drop_component(page, "Keuzelijst")
+
+            # Check that the modal is open
+            await expect(page.locator("css=.formio-dialog-content")).to_have_count(1)
```
Comment (sergei-maertens) [inline src/openforms/forms/tests/e2e_tests/test_form_designer.py:385]: I found out about `.to_be_visible()` which is semantically closer than `to_have_count`, but I'll clean that up in a separate PR for all the existing tests I think :thinking:

**Review by sergei-maertens — COMMENTED** [review]
Couple findings while testing :(

* ~~I added a test that shows there's a regression in tracking the translations. We kept a previousLiteralsMap so that when we detect changes in the component options, the translation is not lost. Now it is.~~ fixed in d669333bfee7ad767af7eb852359f84664f66bef
* With a textfield component I'm not getting infinite loops, but I am getting them with a Select component that has the options sourced from a variable.

I will push my console logging so this is observable.

File: src/openforms/js/components/form/edit/options.js [hunk 3]
```diff
@@ -208,6 +208,7 @@ const OPTIONS_CHOICES = [
         },
       },
     ],
+    clearOnHide: true,
```
Comment (sergei-maertens) [inline src/openforms/js/components/form/edit/options.js:211]: I don't believe this contributed anything to breaking the infinite change event loop, but it seems more correct either way.

File: src/openforms/js/components/formio_builder/builder.js [hunk 4]
```diff
@@ -411,12 +391,43 @@ const FormIOBuilder = ({
...
+    const {instance} = changed;
+
+    if (!flags.fromSubmission) {
+      instance.root.triggerChange(flags, changed, modifiedByHuman);
+    }
+
+    // we only need to sync translations when an actual human changed some literal
+    if (!modifiedByHuman) {
+      return;
+    }
```
Comment (sergei-maertens) [inline src/openforms/js/components/formio_builder/builder.js:409]: partially fixes some of the infinite change event triggers, but in generally this seems a bit of a safer approach - we only translate literals that are entered by the form designer, and don't even bother with automatically updated 'literals' since those aren't translated anyway.

Aborting here reduces the risk of change trigger cascades.

File: src/openforms/js/components/formio_builder/builder.js [hunk 5]
```diff
@@ -450,7 +461,6 @@ const FormIOBuilder = ({
       form={formRef.current}
       options={builderOptions}
       onChange={formSchema => onChange(cloneDeep(formSchema))}
-      onUpdateComponent={() => (previousLiteralsRef.current = {})}
```
Comment (sergei-maertens) [inline src/openforms/js/components/formio_builder/builder.js:453]: this fires more often than expected/anticipated and it seems to work without :shrug:

File: src/openforms/js/components/formio_builder/translation.js [hunk 6]
```diff
@@ -241,7 +242,9 @@ export const handleComponentValueLiterals = (
       return null;
   }
   let translations = {};
-  values.forEach(({label}, index) => {
+  const nonEmptyValues = values.filter(item => !isEmpty(item));
+  if (!nonEmptyValues.length) return null;
+  nonEmptyValues.forEach(({label = ''}, index) => {
```
Comment (sergei-maertens) [inline src/openforms/js/components/formio_builder/translation.js:247]: this is the crucial fix for the infinite loops - looks like formio for its data values has a default value of `[{}`], so the `label` inside the object is undefined. It uses that even if we have the data source set to variable rather than literal options.

It looks like the `undefined` label then caused an infinite cycle of change triggers. Filtering out these empty objects (there's no literal to translate anyway) stopped the infinite loops.

File: src/openforms/js/components/formio_builder/builder.js (hunk 4 above)
Comment (sergei-maertens) [reply src/openforms/js/components/formio_builder/builder.js]: this broke the translations update completely again so I removed it :grimacing:

**Review by sergei-maertens — APPROVED** [review]
