### PR TITLE
[#3422] Prevent broken logic rule to break admin

### LINKED ISSUE #3422: Removing variables/fields can cause Logic tab to crash
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

Sentry: 337920
Utr: 112

Removing fields, groups or steps that are in use in the logic tab can cause the logic tab to crash, in turn breaking the form. 
The only way to fix it is to export the form, remove logic rules that contain the unused variables and import again.

When trying to import a form in this state you see the error: 
`Er is iets foutgegaan bij het importeren van formulier: {'json_logic_trigger': [ErrorDetail(string='De opgegeven variabele is niet aanwezig in het formulier', code='invalid')]}`

unsure about conditions on how to reproduce

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #3422 

- [x] Add error boundary per rule showing the JSON of the rule for debugging purposes

Screenshot from 2023-09-07 15-11-49

- [x] Fix root cause

Screenshot from 2023-09-07 16-15-37

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/FormLogic.js [hunk 1]
```diff
@@ -364,6 +303,23 @@ const Rule = ({
...
+                      description="Warning missing trigger step"
+                      defaultMessage="The selected trigger step could not be found in this form!
+                      Please change it by clicking on the cog icon here on the left."
+                    />
+                  ),
+                  level: 'warning',
+                },
+              ]}
+            />
+          )}
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/FormLogic.js:321]: Is there a way we can pass this in so that the cog icon is automatically expanded and the warning shown with the relevant field, instead of having this indirect message?

File: src/openforms/js/components/admin/form_design/FormLogic.js [hunk 2]
```diff
@@ -385,6 +341,137 @@ const Rule = ({
...
+      </div>
+
+      <div className="logic-rule-error__json">
+        {JSON.stringify({
+          jsonLogicTrigger,
+          triggerFromStepIdentifier,
+          order,
+          actions,
+          isAdvanced,
+        })}
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/FormLogic.js:410]: wrapping this in `<code><pre>...</pre></code>` might make it look a tad better?

File: src/openforms/js/components/admin/form_design/FormLogic.js [hunk 3]
```diff
@@ -385,6 +341,137 @@ const Rule = ({
...
+  jsonLogicTrigger,
+  triggerFromStep: triggerFromStepIdentifier,
+  actions,
+  isAdvanced,
+  onChange,
+  onDelete,
+  errors = {},
+}) => {
+  const intl = useIntl();
+  const [displayAdvancedOptions, setDisplayAdvancedOptions] = useState(false);
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/FormLogic.js:376]: I think we could do the broken-trigger-from-step detection here and then you can immediately call `setDisplayAdvancedOptions(true)` if that's the case (or use that state as initial state value :thinking: )

File: src/openforms/js/components/errors/ErrorMessage.js [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+        <FAIcon icon="exclamation-circle" title="error" />
+      </span>
+      <div className="error-message__children">{children}</div>
+    </div>
+  );
+};
+
+ErrorMessage.propTypes = {
+  children: PropTypes.node,
+  modifiers: PropTypes.arrayOf(PropTypes.string),
```
Comment (sergei-maertens) [inline src/openforms/js/components/errors/ErrorMessage.js:20]: unused :)

File: src/openforms/scss/components/admin/_index.scss [hunk 5]
```diff
@@ -38,3 +39,6 @@
 
 // Submission logs
 @import './logic-evaluated-table';
+
+// Errors
+@import 'error-message';
```
Comment (sergei-maertens) [inline src/openforms/scss/components/admin/_index.scss:44]:
```suggestion
@import './error-message';
```
bit of consistency :)

File: src/openforms/js/components/admin/form_design/FormLogic.js (hunk 3 above)
Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/FormLogic.js:376]: Mhmmm I wanted to have as much logic as possible inside the error boundary, so that if something unexpected goes wrong it doesn't break the page but the action to delete is still visible :thinking: Maybe I can pass `setDisplayAdvancedOptions` to `RuleBody`?

Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/FormLogic.js:376]: Screenshot from 2023-09-08 12-08-39

File: src/openforms/js/components/admin/form_design/FormLogic.js (hunk 2 above)
Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/FormLogic.js:410]: Screenshot from 2023-09-08 12-15-04
:tada: 
(I left out the `<pre>` because it was making it go off the page)

File: src/openforms/js/components/admin/form_design/FormLogic.js (hunk 3 above)
Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/FormLogic.js:381]: is this warning also done with error boundary then?

> Maybe I can pass setDisplayAdvancedOptions to RuleBody?

It's an option, but then you'll have to rely on `useEffect` I think and it may conflict with the user click actions that update the state :thinking: 

Error boundaries are really a bit of a last resort btw, it's good to have them because you don't know what will break, but if you can detect error situations and prevent crashes that way, that's always preferred. So that's why I suggested this approach :)

Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/FormLogic.js:381]: > is this warning also done with error boundary then?

No, this error is done by checking if `triggerFromStepIdentifier` is set but `triggerFromStep` is null! 

But what I meant is: the errors tend to come from the logic that is now moved into the `RuleBody` component and wrapped in an error boundary.
If I move the code that checks for the trigger step back to `Rule`, if it breaks unexpectedly it will break the whole page because it will be outside of the error boundary.

Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/FormLogic.js:381]: I think I understand.

Could we maybe perform the check inside the advanced config (the component behind the cog) and force that to be open regardless of the toggle state/prop if there's an error? So then the actual checks are all contained inside the error boundary but we get nicer feedback.

**Review by sergei-maertens — APPROVED** [review]
