### PR TITLE
[#891] Fix logic selectboxes

### LINKED ISSUE #891: Form logic not working for selectBoxes
Raised by municipality LV - Taiga issue 132

This does not work:

logic_fail_again

When using native logic in the "Bestandupload field", it does work. But our customer wants to use it cross form definitions (hence form logic), which is not possible with the native logic. 

Please fix. 

logic_notfail

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes #891 

Todo:

- [x] Think about cases with other operators
- [x] Write tests

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/logic/Trigger.js [hunk 1]
```diff
@@ -90,10 +90,17 @@ const parseJsonLogic = (logic) => {
...
+    let compareValue = values[1];
     let operandType = '';
     let operand = '';
 
+    // Selectboxes case: the component name contains the reference to which value, e.g. "selectComponentField.option1"
+    const splitComponent = component.split('.');
+    if (splitComponent.length > 1) {
+        component = splitComponent[0];
+        compareValue = splitComponent[1];
+    }
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/logic/Trigger.js:102]: probably a bit too naive, since you can set up the `key` to be something like `foo.bar` which results in the following submission data:

```json
{"foo": {"bar": "<value>"}}
```

(that's how Formio tranforms it, using `lodash/set` under the hood)

A more robust approach will probably be:

```js
[component, ...compareValueBits] = component.split('.')
```

& then when building the `firstOperand`, you could just `compareValueBits.join('.')` again

File: src/openforms/submissions/tests/form_logic/test_modify_components.py [hunk 2]
```diff
@@ -958,6 +958,54 @@ def test_dirty_data_only_diff_data_returned(self):
...
+                ]
+            },
+        )
+        FormLogicFactory.create(
+            form=form,
+            json_logic_trigger={
+                "==": [
+                    {"var": "currentPets.cat"},
+                    True,
+                ]
```
Comment (sergei-maertens) [inline src/openforms/submissions/tests/form_logic/test_modify_components.py:985]: I don't think we can actually specify boolean values at the moment in the logic builder, they get interpreted as a string. Not sure if json-logic package handles this conversion?

**Review by sergei-maertens — CHANGES_REQUESTED** [review]

File: src/openforms/js/components/admin/form_design/logic/Trigger.js (hunk 1 above)
Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/logic/Trigger.js]: While updating this, I noticed that my change in the backed also breaks in case of components with dots in the key names. So I made changes there too. I changed a bit approach in the front end

File: src/openforms/submissions/tests/form_logic/test_modify_components.py (hunk 2 above)
Comment (SilviaAmAm) [reply src/openforms/submissions/tests/form_logic/test_modify_components.py:985]: Because of this: https://github.com/open-formulieren/open-forms/blob/fix/891-logic-selectboxes/src/openforms/js/components/admin/form_design/logic/Trigger.js#L276 the value is automatically set to a bool in the admin. It's a bit hackish maybe :sweat_smile:

Comment (sergei-maertens) [reply src/openforms/submissions/tests/form_logic/test_modify_components.py:985]: Hrm, so that makes it not possible to attach logic if the value is `false` instead of `true`?

File: src/openforms/js/components/admin/form_design/logic/Trigger.js [hunk 3]
```diff
@@ -261,8 +267,20 @@ const Trigger = ({ name, logic, onChange }) => {
...
+    switch (componentType) {
+        case 'date': {
+            firstOperand = {date: {var: triggerComponent}};
+            break;
+        }
+        case 'selectboxes': {
+            firstOperand = {var: `${triggerComponent}.${compareValue}`}
+            compareValue = true;
+            break;
+        }
```
Comment (sergei-maertens) [inline src/openforms/js/components/admin/form_design/logic/Trigger.js:280]: Either we should:

- Parse the strings `"false"` and `"true"` from text-input as booleans `false` and `true` or
- Offer a dropdown for type selectboxes component where they can select `True` or `False` which maps to the booleans under the hood (preferred approach)

With the select boxes there's only two states - checked or not checked and you can attach logic to both. By always setting it to checked, you're taking away the option to do something if it's _not_ checked.

**Review by sergei-maertens — CHANGES_REQUESTED** [review]

File: src/openforms/submissions/tests/form_logic/test_modify_components.py (hunk 2 above)
Comment (SilviaAmAm) [reply src/openforms/submissions/tests/form_logic/test_modify_components.py:985]: I thought that in that case you can use the `!=` operator

**Review by sergei-maertens — APPROVED** [review]

File: src/openforms/js/components/admin/form_design/logic/Trigger.js (hunk 3 above)
Comment (SilviaAmAm) [reply src/openforms/js/components/admin/form_design/logic/Trigger.js:280]: I thought that since the logic boxes only have 2 states, you can achieve the logic for when the checkbox is unselected by using the `!=` operator
