### PR TITLE
[#2062] Moved the "Print this page" click handler to new public.js exernal javascript bundle to satisfy CSP

### LINKED ISSUE #2062: "Pagina afdrukken" blocked by CSP
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When trying to print a page CSP is triggered preventing the window.print() command to execute.

```json

{
  "csp-report": {
    "document-uri": "https://open-formulieren-test.domein.nl/form/",
    "referrer": "",
    "violated-directive": "script-src-elem",
    "effective-directive": "script-src-elem",
    "original-policy": "default-src 'self'; img-src 'self' data: https://service.domain.nl/; style-src 'self' 'nonce-3nRQ5zYUpD131Zux7qupVw=='; script-src 'self' 'nonce-3nRQ5zYUpD131Zux7qupVw=='; frame-ancestors 'self'; base-uri 'self'; frame-src 'self'; report-uri /csp/report/",
    "disposition": "enforce",
    "blocked-uri": "inline",
    "line-number": 1,
    "source-file": "https://open-formulieren-test.domein.nl/form/",
    "status-code": 200,
    "script-sample": ""
  }
}

```

### Stappen om te reproduceren / Steps to reproduce

Click "Pagina Afdrukken" from the a11y toolbar and watch console print the CSP error.

### Verwacht gedrag / Expected behavior

The browser should initiate a print screen to print the current page.

### Screen resolution

_No response_

### Device

Desktop

### OS

Linux

### Browser

Chrome, Firefox

### PR DESCRIPTION
**Pull request by Bartvaderkin**
Fixes #2062

### CODE REVIEW

File: src/openforms/js/public.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+document.addEventListener('DOMContentLoaded', event => {
```
Comment (sergei-maertens) [inline src/openforms/js/public.js:1]: so turns out that this approach is to be preferred:

```
if (document.readyState !== 'loading') {
  init();
} else {
  document.addEventListener('DOMContentLoaded', init);
}
```

... probably we should write a utility `onLoaded` function for that so we can just do `onLoaded(init);` at the end of the module.

**Review by sergei-maertens — APPROVED** [review]
