### PR TITLE
[#5039] Fix email registration errors

### LINKED ISSUE #5039: Not setting plain text in email registration, leads to error with no visible error message (nonFieldErrors worden niet getoond).

### PR DESCRIPTION
**Pull request by vaszig**
Closes #5039

**Changes**

- Email registration used `nonField` errors for a combination of fields and these were not shown on the frontend. Fixed these by showing them on the top of the modal.

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Dockerfile/scripts

  - [x] Updated the Dockerfile with the necessary scripts from the `./bin` folder

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js [hunk 1]
```diff
@@ -34,8 +35,17 @@ const EmailOptionsFormFields = ({name, schema}) => {
   ).map(([value, label]) => ({value, label}));
 
   const relevantErrors = filterErrors(name, validationErrors);
+  const nonFieldErrors = relevantErrors.filter(([field]) => field.includes('nonFieldErrors'));
```
Comment (viktorvanwijk) [inline src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js:38]: Is there a reason why you included the parentheses and brackets in `([field])`? It would also work without them, right?

File: src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js [hunk 2]
```diff
@@ -34,8 +35,17 @@ const EmailOptionsFormFields = ({name, schema}) => {
...
+
   return (
     <ValidationErrorsProvider errors={relevantErrors}>
+      {nonFieldErrors && (
+        <>
+          {nonFieldErrors.map(([_, message], index) => (
```
Comment (viktorvanwijk) [inline src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js:44]: `index` doesn't seem to be used. Is there a reason you included it?

**Review by viktorvanwijk — COMMENTED** [review]
Works as expected :). As you already pointed out, though,  might be nice if there is a solution which will work for all option forms, not only this plugin.

File: src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js (hunk 2 above)
Comment (vaszig) [reply src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js:44]: No, I had included this because I thought I would use it for the key, I can remove it.

File: src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js (hunk 1 above)
Comment (vaszig) [reply src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js:38]: The brackets are there because it means that each item in `relevantErrors` is expected to be an array, and we are extracting the first element.

Comment (viktorvanwijk) [reply src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js:38]: Wouldn't it make more sense to do a string comparison then, instead of a `.includes`?

File: src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js (hunk 2 above)
Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/registrations/email/EmailOptionsFormFields.js:44]: whenever you `array.map(foo => <component />)`, the component must get the `key`. See https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key

**Review by sergei-maertens — APPROVED** [review]

**Comment by sergei-maertens** [comment]
Accepting this as it is - I think with the UX rework we'll have the chance to fix this properly so that you don't have to think about it at all anymore.

**Comment by sergei-maertens** [comment]
Backports:

* 3.0.x: 4b1ecdf60b99b54711f1041f790d03d52e4b11f3
* 2.8.x: skipped as it didn't have the UX rework yet
