### PR TITLE
DMN fixes

### LINKED ISSUE #4278: (Suspected) issues in DMN configuration admin
Business topic: DMN

* Configuring in/output variable mappings and then changing the decision definition to use -> doesn't clear the mapping. The dropdowns can't find the input/output variables and render in "empty" state, but there still *is* configuration behind the scenes.
* Removing a form variable likely does not remove it from the DMN input/output variable mappings
* A parameter that was removed in the decision definition (in a new version, for example, or renamed) is not cleared (similar to the two cases above)

Some UI controls to show there is still data with a dead reference is probably in order, the user can then decide to remove or update the mapping?

- [x] Clear mapping when decision definition is changed
- [x] Reset mapping for version changes (in modal)
- [x] Handle removing/editing of form variables (component + user defined)
    - [x] Reset form variable for input/output variable when a form variable is deleted
    - [x] Detect incomplete mappings and display a warning icon on:
        - the logic tab
        - the logic rule affected
        - the logic action for DMN affected
        - inside the modal when the DMN configuration modal is opened
    - [x] Update the key for changes in variables/components

### PR DESCRIPTION
**Pull request by sergei-maertens**
Closes #4278

**Changes**

* Display warning icons on logic tab & next to logic actions for invalid/incomplete DMN parameter mappings
* When a variable/component is deleted, clear the DMN mappings that have a reference (which triggers the above)
* When a variable/component key is renamed, update the DMN mappings to point to the new key
* Added a bunch more stories and refactored some components to be more/better re-usable

**Checklist**

Check off the items that are completed or not relevant.

- Impact on features

  - [x] Checked copying a form
  - [x] Checked import/export of a form
  - [x] Config checks in the configuration overview admin page
  - [x] Problem detection in the admin email digest is handled

- Release management

  - [x] I have labelled the PR as "needs-backport" accordingly

- I have updated the translations assets (you do NOT need to provide translations)

  - [x] Ran `./bin/makemessages_js.sh.sh`
  - [x] Ran `./bin/compilemessages_js.sh`

- Commit hygiene

  - [x] Commit messages refer to the relevant Github issue
  - [x] Commit messages explain the "why" of change, not the how

### CODE REVIEW

File: src/openforms/js/components/admin/form_design/logic/actions/Actions.js [hunk 1]
```diff
@@ -347,4 +348,37 @@ ActionComponent.propTypes =
       onChange: PropTypes.func.isRequired,
     };
 
+export const detectProblems = (action, intl) => {
+  switch (action.action.type) {
```
Comment (vaszig) [inline src/openforms/js/components/admin/form_design/logic/actions/Actions.js:352]: I would use a simple if statement here since we have only one case, do we use switch for possible update in the code?

File: src/openforms/js/components/admin/form_design/logic/actions/dmn/VariableMapping.js [hunk 2]
```diff
@@ -85,7 +91,7 @@ const VariableMapping = ({
   alreadyMapped = [],
 }) => {
   const intl = useIntl();
-  const {getFieldProps, values} = useFormikContext();
+  const {values} = useFormikContext();
 
   const confirmationMessage = intl.formatMessage({
```
Comment (vaszig) [inline src/openforms/js/components/admin/form_design/logic/actions/dmn/VariableMapping.js:96]: Already there before your PR but if you change something else we can remove this I guess.

**Review by vaszig — APPROVED** [review]

File: src/openforms/js/components/admin/form_design/logic/actions/Actions.js (hunk 1 above)
Comment (sergei-maertens) [reply src/openforms/js/components/admin/form_design/logic/actions/Actions.js:352]: yeah, I'm doing it for consistency and future problem detection in other action types!
